image:
  repository: chartmuseum/chartmuseum
  tag: v0.11.0

env:
  open:
    STORAGE: amazon
    STORAGE_AMAZON_BUCKET: chart-museum-bucket
    STORAGE_AMAZON_REGION: eu-central-1
    DISABLE_API: false
  secret:
    BASIC_AUTH_USER:
    BASIC_AUTH_PASS:

## Ingress for load balancer
ingress:
  enabled: true
  labels:
    dns: "route53"
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "false"
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - name: chartmuseum-test.example.com
      path: /
      tls: false

replica:
  annotations:
    iam.amazonaws.com/role: "arn:aws:iam::xxxx:role/chart-museum-role"