{{- if .Values.configfiles }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-files
  labels:
    app: {{ $.Release.Name }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": '-99'
    "helm.sh/hook-delete-policy": before-hook-creation
data:
{{- range $config, $configrefs := $.Values.configfiles  }}
  {{ $config }}: |-
{{ $configrefs.data | indent 4}}
{{- end }}
{{- end }}
