{{- if .Values.envconfig }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  labels:
    app: {{ .Release.Name }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": '-99'
    "helm.sh/hook-delete-policy": before-hook-creation
data:
{{- range $key, $val := .Values.envconfig }}
  {{ $key }}: |-
{{ $val | indent 4 }}
{{- end }}
{{- end }}