{{ if  $.Values.secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Release.Name }}-secret
  labels:

    release:  {{ $.Release.Name }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": '-99'
    "helm.sh/hook-delete-policy": before-hook-creation
data:
{{- range $key, $val := .Values.secret.data }}
  {{ $key }}: |-
{{ $val | indent 4}}
{{- end }}
{{- end}}
